#!/bin/bash

# ZAT-Docker alias

port=4567
args=()

while [ "$#" -gt 0 ]; do
  case "$1" in
    --port=*)
      port="${1#*=}"
      shift
      ;;
    --port)
      if [ -n "$2" ]; then
        port="$2"
        shift 2
      else
        break
      fi
      ;;
    *)
      args+=("$1")
      shift
      ;;
  esac
done

if [ "$port" -ne 4567 ]; then
  args+=("--port" "$port")
fi

docker run -it --rm -u "$(id -u):$(id -g)" -p "${port}:${port}" -v "$(pwd)":/data mdebortoli/zat-docker zat "${args[@]}"
